### ISSUE TITLE
Need to use Ruby version >= 2.2.2 .

### ISSUE THREAD

**Issue by ihorie** [team-LetTheWookieWin/chess-app#2]
Build is failing because we don't have .travis.yml file and the default is ruby 1.9.3p551.
I think we need to use Ruby version >= 2.2.2

**Comment by DrKalen** [comment]
II understand it right, Travis CI will keep failing until we give it some tests to run that our app can pass. Maybe ALSO need to update ruby version? How about that, Jacob?

**Comment by jacobwgillespie** [comment]
Yep, the build will fail until we have rspec, and yeah we will need to bump the Ruby version for Travis as well

**Comment by ihorie** [comment]
@DrKalen To be accurate,Travis CI won't fail even the source code doesn't have a test. It was failing because Travis CI uses 1.9.x by default and some gems need ruby version >= 2.2.x. The reason why PR #6 fails is different. It fails because .travis.yml was configured to use rspec and rubocop but those gems are not required in Gemfile in "travisci" branch. I think it will work after PR #4 and #5 are merged.

**Comment by DrKalen** [comment]
Ah, I see. thanks for clearing that up.

Best,
Kalen


Dr. Kalen Hammann ("Dr. K")
Communication Specialist
Ofc:727-733-2178
Cell: 1-303-589-7107
See clips at www.BookDrK.com <http://www.bookdrk.com/>

**Comment by ihorie** [comment]
I close this issue since we have .travis.yml now.
